--- @class LogicCode
LogicCode = {
    SUCCESS = 0, -- action is completed without errors
    FAIL = 1, -- unknown error is occurred, action can't be completed SERVER_ERROR = 2, server can't serve the request
    SERVER_ERROR = 2, -- server can't serve the request
    FEATURE_NOT_IMPLEMENTED = 3, -- this feature is not existed

    PLAYER_NOT_FOUND = 4, -- player can't be found
    INVALID_INPUT_DATA = 5, -- input data of request is in invalid format
    NOT_ENOUGH_RESOURCES = 6, -- the desired action can't be completed because lack of a specific resource

    HANDSHAKE_CLIENT_TIME_INVALID = 11,
    HANDSHAKE_CLIENT_VERSION_FORBIDDEN = 12,
    HANDSHAKE_BUNDLE_NAME_FORBIDDEN = 13,
    HANDSHAKE_SHARED_SECRET_INVALID = 14,
    HANDSHAKE_CHALLENGE_INVALID = 15,
    HANDSHAKE_NUMBER_CSV_FILE_MISMATCHED = 16,
    HANDSHAKE_CSV_HASH_MISMATCHED = 17,


    AUTH_ALREADY_REGISTERED = 30,
    AUTH_ANOTHER_ACCOUNT_ALREADY_BOUND = 31,
    AUTH_SAME_ACCOUNT_ALREADY_BOUND = 32,
    AUTH_PASSWORD_MISMATCHED = 34,
    AUTH_PLAYER_BANNED = 35,
    AUTH_SERVER_ID_INVALID = 36,
    AUTH_ACCOUNT_USER_NAME_NOT_FOUND = 37,
    AUTH_PASSWORD_MISMATCHED_LIMIT_REACHED = 38,

    AUTH_ALREADY_BINDED = 40,
    AUTH_PASSWORD_ALREADY_USED = 41,
    AUTH_ACCOUNT_LOCATION_ABUSED = 42,


    PLAYER_NAME_FORMAT_INVALID = 50,
    PLAYER_NAME_ALREADY_BANNED = 51,
    PLAYER_USER_NAME_ALREADY_EXISTED = 52,
    PLAYER_ALREADY_BLOCKED = 53,
    PLAYER_ALREADY_UNBLOCKED = 54,
    PLAYER_BLOCK_LIST_LIMIT_REACHED = 55,
    PLAYER_FACEBOOK_ID_ALREADY_EXISTED = 56,
    PLAYER_APPLE_ID_ALREADY_EXISTED = 57,
    PLAYER_NAME_INVALID = 58,
    PLAYER_VIP_NOT_MATCHED = 59,
    PLAYER_GOOGLE_ID_ALREADY_EXISTED = 60,
    PLAYER_SUN_GAME_ID_ALREADY_EXISTED = 61,


    HERO_COLLECTION_FULL = 70,
    HERO_LEVEL_LIMIT_REACHED = 71,
    HERO_STAR_LIMIT_REACHED = 72,
    HERO_NOT_FOUND = 73,
    HERO_ALREADY_LOCKED = 74,
    HERO_EVOLVE_MATERIAL_INVALID = 75,
    HERO_EVOLVE_FOOD_NOT_ENOUGH = 77,
    HERO_ALREADY_IN_AUTO_TRAINING = 78,
    HERO_ALREADY_IN_RAISED_HERO = 79,


    DAILY_REWARD_ALREADY_CLAIMED = 80,


    ALTAR_CAN_NOT_DISASSEMBLE = 85,
    ALTAR_CAN_NOT_RESET = 86,


    HERO_FRAGMENT_NOT_ENOUGH = 90,
    HERO_FRAGMENT_NOT_FOUND = 91,


    PROPHET_TREE_HERO_CAN_NOT_CONVERT = 100,
    PROPHET_TREE_CONVERTED_HERO_NOT_FOUND = 101,
    PROPHET_TREE_HERO_ALREADY_IN_RAISED_HERO = 102,


    SUMMON_SCROLL_CAN_NOT_BUY = 110,


    ITEM_HERO_LEVEL_NOT_ENOUGH = 120,
    ITEM_LEVEL_LIMIT_REACHED = 121,
    ITEM_NOT_FOUND = 123,
    SKIN_CAN_NOT_EQUIP = 124,


    RAID_TURN_BUY_LIMIT_REACHED = 130,
    RAID_STAGE_NOT_FOUND = 131,
    RAID_LEVEL_NOT_ENOUGH = 132,


    DUNGEON_HERO_ALREADY_BOUND = 140,
    DUNGEON_HERO_ALREADY_DEAD = 141,
    DUNGEON_HERO_NOT_BOUND = 142,
    DUNGEON_SHOP_NOT_FOUND = 143,
    DUNGEON_NOT_OPEN = 144,
    DUNGEON_BINDING_HERO_INVALID = 145,
    DUNGEON_HERO_SLOT_INVALID = 146,
    DUNGEON_HERO_NOT_FOUND = 148,
    DUNGEON_BUFF_ITEM_NOT_FOUND = 149,
    DUNGEON_STAGE_LIMIT_REACHED = 150,
    DUNGEON_STAGE_INVALID = 151,
    DUNGEON_STAGE_NOT_REACHED = 152,
    DUNGEON_BUFF_ALREADY_PICKED = 153,
    DUNGEON_BUFF_NOT_GENERATED = 154,
    DUNGEON_BUFF_ITEM_LIMITED = 155,
    DUNGEON_BUFF_SMASH_NOT_COMPLETED = 156,
    DUNGEON_BUFF_PICK_INDEX_INVALID = 157,
    DUNGEON_BUFF_ITEM_CAN_NOT_USE = 158,


    MASTERY_LEVEL_LIMIT_REACHED = 160,
    MASTERY_MILESTONE_LOCKED = 164,


    SUMMONER_CLASS_CAN_NOT_SELECT = 171,
    SUMMONER_SKILL_TIER_CAN_NOT_SELECT = 172,
    SUMMONER_STAR_LIMIT_REACHED = 173,


    CASINO_PREMIUM_CHIP_CAN_NOT_BUY = 180,
    CASINO_BASIC_CHIP_BUY_LIMIT_REACHED = 181,


    HAND_OF_MIDAS_CAN_NOT_CLAIM = 190,


    TOWER_STAMINA_LIMIT_REACHED = 200,
    TOWER_STAGE_LIMIT_REACHED = 201,
    TOWER_STAGE_INVALID = 202,


    TAVERN_NO_QUEST_CAN_REROLL = 210,
    TAVERN_QUEST_CAN_NOT_CHANGE_LOCK = 211,
    TAVERN_QUEST_CAN_NOT_CANCEL = 212,
    TAVERN_QUEST_CAN_NOT_START = 213,
    TAVERN_QUEST_NOT_FOUND = 214,
    TAVERN_HERO_ANOTHER_QUEST_ALREADY_JOINED = 215,
    TAVERN_QUEST_REQUIREMENT_NOT_FULFILLED = 216,
    TAVERN_QUEST_NOT_COMPLETED = 217,
    TAVERN_QUEST_ALREADY_COMPLETED = 218,
    TAVERN_QUEST_LIMIT_REACHED = 219,
    TAVERN_QUEST_CAN_NOT_SPEED_UP = 220,


    FEATURE_LOCKED = 230,


    CAMPAIGN_AUTO_TRAIN_SLOT_EXCEEDED = 240,
    CAMPAIGN_STAGE_INVALID = 241,
    CAMPAIGN_STAGE_NOT_FOUND = 242,
    CAMPAIGN_QUICK_BATTLE_TICKET_NOT_FOUND = 243,
    CAMPAIGN_TRAIN_HERO_STAR_INVALID = 244,
    CAMPAIGN_TRAIN_SLOT_EMPTY = 245,
    CAMPAIGN_LEVEL_NOT_ENOUGH = 246,
    CAMPAIGN_QUICK_BATTLE_LIMIT_REACHED = 247,
    CAMPAIGN_TRAIN_HERO_ALREADY_IN_RAISED_HERO = 248,


    FRIEND_ALREADY_EXISTED = 250,
    FRIEND_REQUEST_ALREADY_EXISTED = 251,
    FRIEND_FULL = 252,
    FRIEND_NOT_FOUND = 253,
    FRIEND_REQUEST_NOT_FOUND = 254,
    FRIEND_CAN_NOT_SCOUT = 255,
    FRIEND_SCOUT_RATE_NOT_FOUND = 256,
    FRIEND_NUMBER_RAID_LIMIT_REACHED = 260,
    FRIEND_TARGET_FULL = 262,
    FRIEND_REQUEST_FULL = 263,

    FRIEND_POINT_LIMIT_REACHED = 265,
    FRIEND_POINT_NOTHING_TO_RECEIVE = 266,


    MAIL_SEND_LIMIT_REACHED = 270,
    MAIL_NOT_FOUND = 271,
    MAIL_CAN_NOT_DELETE = 272,
    MAIL_REWARD_CAN_NOT_RECEIVE = 273,
    MAIL_LENGTH_INVALID = 274,


    ARENA_OPPONENT_NOT_FOUND = 290,
    ARENA_FORMATION_NOT_SET = 291,
    ARENA_TICKET_BUY_LIMIT_REACHED = 292,
    ARENA_SEASON_REWARD_NOT_FOUND = 293,
    ARENA_BOT_OPPONENT_NOT_FOUND = 294,


    RECORD_NOT_FOUND = 300,


    CHAT_FORBIDDEN = 310,
    CHAT_LENGTH_INVALID = 311,


    REWARD_VIDEO_REWARD_NOT_FOUND = 320,
    REWARD_VIDEO_LIMIT_REACHED = 321,


    REMOTE_CONFIG_KEY_NOT_FOUND = 330,
    REMOTE_CONFIG_VALUE_TYPE_MISMATCHED = 331,


    LANGUAGE_NOT_SUPPORTED = 340,


    GUILD_ALREADY_JOINED = 350,
    GUILD_NOT_FOUND = 351,
    GUILD_PLAYER_IN_BLOCK_DURATION = 352,
    GUILD_MEMBER_FULL = 353,
    GUILD_MEMBER_NOT_FOUND = 354,
    GUILD_CAN_NOT_LEAVE = 355,
    GUILD_ALREADY_LEFT = 356,

    GUILD_NAME_FORMAT_INVALID = 360,
    GUILD_NAME_ALREADY_BANNED = 361,
    GUILD_NAME_ALREADY_EXISTED = 362,
    GUILD_DESCRIPTION_FORMAT_INVALID = 363,
    GUILD_DESCRIPTION_ALREADY_BANNED = 364,

    GUILD_CREATOR_LEVEL_NOT_ENOUGH = 370,
    GUILD_PERMISSION_FORBIDDEN = 371,
    GUILD_SUB_LEADER_LIMIT_REACHED = 372,
    GUILD_MEMBER_ALREADY_CHECK_IN = 373,
    GUILD_MEMBER_INACTIVE_TOO_LONG = 376,

    GUILD_APPLICATION_ALREADY_EXISTED = 380,
    GUILD_APPLICATION_FULL = 381,
    GUILD_APPLICATION_NOT_FOUND = 382,

    GUILD_BOSS_NOT_FOUND = 400,
    GUILD_BOSS_ALREADY_CHALLENGED = 401,
    GUILD_BOSS_CHALLENGE_FORBIDDEN = 402,
    GUILD_BOSS_CAN_NOT_SELECT = 403,
    GUILD_BOSS_MONTHLY_STATISTICS_NOT_FOUND = 404,

    GUILD_DUNGEON_ALREADY_CHALLENGED = 410,
    GUILD_DUNGEON_NOT_FOUND = 411,
    GUILD_DUNGEON_STAGE_NOT_FOUND = 412,
    GUILD_DUNGEON_NOT_OPEN = 413,
    GUILD_DUNGEON_STAGE_ALREADY_COMPLETED = 414,

    GUILD_WAR_OPPONENT_NOT_REGISTERED = 420,
    GUILD_WAR_ALREADY_REGISTERED = 421,
    GUILD_WAR_OPPONENT_NOT_FOUND = 422,
    GUILD_WAR_OPPONENT_INVALID = 423,
    GUILD_WAR_NUMBER_MEMBER_MISMATCHED = 424,
    GUILD_WAR_OPPONENT_CAN_NOT_BE_FOUND = 425,
    GUILD_WAR_OPPONENT_CAN_NOT_BE_ATTACKED = 426,
    GUILD_WAR_NOT_REGISTERED = 427,
    GUILD_WAR_NOT_PARTICIPATED = 428,

    GUILD_WAR_PHASE_1_CLOSED = 430,
    GUILD_WAR_PHASE_2_CLOSED = 431,
    GUILD_WAR_PHASE_3_CLOSED = 432,

    QUEST_NOT_FOUND = 450,
    QUEST_REWARD_CAN_NOT_CLAIM = 451,
    QUEST_UNLOCK_REQUIREMENT_NOT_COMPLETED = 452,


    MARKET_ITEM_NOT_FOUND = 460,
    MARKET_ITEM_SOLD_OUT = 461,
    MARKET_TYPE_INVALID = 462,
    MARKET_UPGRADE_LEVEL_INVALID = 463,


    FORMATION_INVALID = 470,


    AVATAR_NOT_FOUND = 480,
    AVATAR_FRAME_NOT_FOUND = 481,


    TUTORIAL_STEP_NOT_FOUND = 490,


    PASSWORD_EMAIL_SEND_LIMIT_REACHED = 501,
    PASSWORD_CODE_ENTER_LIMIT_REACHED = 502,

    PASSWORD_CODE_EXPIRED = 503,
    PASSWORD_CODE_MISMATCHED = 504,


    EMAIL_SEND_LIMIT_REACHED = 510,
    EMAIL_CODE_ENTER_LIMIT_REACHED = 511,

    EMAIL_VALIDATION_CODE_EXPIRED = 512,
    EMAIL_VALIDATION_CODE_MISMATCHED = 513,

    EMAIL_ALREADY_EXISTED = 514,

    EMAIL_CAN_NOT_SEND = 515,
    EMAIL_ALREADY_VERIFIED = 516,
    EMAIL_NOT_FOUND = 517,
    EMAIL_NOT_VERIFIED = 518,


    DEFENSE_MODE_INPUT_DATA_INVALID = 550,
    DEFENSE_MODE_HERO_NOT_BOUND = 551,
    DEFENSE_MODE_LAND_INVALID = 552,
    DEFENSE_MODE_STAGE_INVALID = 553,
    DEFENSE_MODE_ROAD_INVALID = 554,
    DEFENSE_MODE_BIND_POSITION_INVALID = 555,
    DEFENSE_MODE_HERO_FACTION_INVALID = 556,
    DEFENSE_MODE_LAND_NOT_UNLOCK = 557,
    DEFENSE_MODE_REACHED_MAX_STAGE = 558,
    DEFENSE_MODE_LEVEL_UPGRADE_INVALID = 559,
    DEFENSE_MODE_BIND_HERO_DUPLICATE = 560,
    DEFENSE_MODE_STAGE_NOT_COMPLETED = 561,
    DEFENSE_MODE_WAVE_INVALID = 562,


    RAISE_HERO_NOT_UNLOCK = 570,
    RAISE_HERO_CAN_NOT_BIND = 571,
    RAISE_HERO_INVALID_INPUT_DATA = 572,
    RAISE_HERO_BIND_HERO_DUPLICATED = 573,
    RAISE_HERO_BIND_PENTAGRAM_EXISTED = 574,

    HERO_LINKING_HERO_INVALID = 580,
    HERO_LINKING_SUPPORT_HERO_DUPLICATED = 581,
    HERO_LINKING_COUNTDOWN_NOT_COMPLETED = 582,
    HERO_LINKING_SLOT_INVALID = 583,
    HERO_LINKING_INVALID_INPUT_DATA = 584,
    HERO_LINKING_FRIEND_INVALID = 585,

    PURCHASE_PACK_NOT_FOUND = 600,
    PURCHASE_TRANSACTION_INVALID = 601,
    PURCHASE_PACK_NOT_AVAILABLE = 603,
    PURCHASE_PACK_SOLD_OUT = 604,
    PURCHASE_TRANSACTION_ALREADY_PROCESSED = 605,
    PURCHASE_TRANSACTION_NOT_SUPPORTED = 606,
    PURCHASE_TRANSACTION_NOT_FOUND = 607,
    PURCHASE_SUBSCRIPTION_TRIAL_NOT_AVAILABLE = 608,
    PURCHASE_SUBSCRIPTION_TRIAL_FORBIDDEN = 609,
    PURCHASE_FORBIDDEN = 610,

    PURCHASE_GROWTH_PACK_LINE_NOT_FOUND = 620,
    PURCHASE_GROWTH_PACK_NOT_BUY = 621,
    PURCHASE_GROWTH_PACK_MILE_STONE_NOT_FOUND = 622,
    PURCHASE_GROWTH_PACK_MILE_STONE_OUT_OF_STOCK = 623,
    PURCHASE_GROWTH_PACK_MILE_STONE_LEVEL_NOT_ENOUGH = 624,

    REGRESS_HERO_STAR_NOT_ENOUGH = 630,


    COMEBACK_FEATURE_NOT_ACTIVE = 640,
    COMEBACK_DATA_NOT_FOUND = 641,
    COMEBACK_LOGIN_ALREADY_CLAIMED = 642,
    COMEBACK_LOGIN_REWARD_INVALID = 643,


    DOMAINS_CONTRIBUTE_HERO_DUPLICATED = 650,
    DOMAINS_CONTRIBUTE_HERO_NOT_EXISTED = 651,
    DOMAINS_CONTRIBUTE_HERO_NUMBER_INVALID = 652,
    DOMAINS_CONTRIBUTE_HERO_CLASS_NOT_MATCH = 653,
    DOMAINS_CREW_PLAYER_NOT_SAVE_FORMATION = 654,

    DOMAINS_CREW_NAME_FORMAT_INVALID = 655,
    DOMAINS_CREW_NAME_ALREADY_BANNED = 656,
    DOMAINS_CREW_DESCRIPTION_FORMAT_INVALID = 657,
    DOMAINS_CREW_DESCRIPTION_ALREADY_BANNED = 658,

    DOMAINS_CREW_ALREADY_JOINED = 660,
    DOMAINS_CREW_NOT_FOUND = 661,
    DOMAINS_NOT_IN_CREW = 662,
    DOMAINS_CREW_MEMBER_NOT_FOUND = 663,
    DOMAINS_CREW_PERMISSION_FORBIDDEN = 664,
    DOMAINS_CREW_ALREADY_IN_BATTLE = 665,
    DOMAINS_CREW_MEMBER_FULL = 666,
    DOMAINS_CREW_ALREADY_DISBAND = 667,
    DOMAINS_CREW_MEMBER_NOT_READY = 668,
    DOMAINS_CREW_MEMBER_NOT_ENOUGH = 669,

    DOMAINS_CREW_INVITATION_ALREADY_EXISTED = 670,
    DOMAINS_CREW_INVITATION_FULL = 671,
    DOMAINS_CREW_INVITATION_NOT_EXISTED = 672,
    DOMAINS_CREW_INVITATION_EXPIRED = 673,

    DOMAINS_CREW_APPLICATION_ALREADY_EXISTED = 675,
    DOMAINS_CREW_APPLICATION_FULL = 676,
    DOMAINS_CREW_APPLICATION_NOT_EXISTED = 677,
    DOMAINS_CREW_APPLICATION_EXPIRED = 678,
    DOMAINS_CREW_PLAYER_IN_BLOCK_DURATION = 679,

    DOMAINS_CREW_READY_CHANGE_BLOCK_DURATION = 680,

    DOMAINS_CONTRIBUTE_HERO_INVALID = 681,
    DOMAINS_CREW_NOT_IN_BATTLE = 682,
    DOMAINS_CREW_PREDEFINE_TEAM_NOT_FOUND = 683,
    DOMAINS_CHALLENGE_MAX_STAGE_REACHED = 684,
    DOMAINS_STAMINA_NOT_ENOUGH = 685,

    EVENT_NOT_OPEN = 700,
    EVENT_DATA_NOT_FOUND = 701,


    EVENT_GUILD_QUEST_QUEST_ALREADY_CLAIMED = 730,
    EVENT_GUILD_QUEST_MIN_DONATION_NOT_ENOUGH = 732,


    EVENT_LOGIN_ALREADY_CLAIMED = 740,


    EVENT_RELEASE_FESTIVAL_REWARD_ALREADY_CLAIMED = 751,
    EVENT_RELEASE_FESTIVAL_REQUIREMENT_NOT_FULFILLED = 752,


    EVENT_EXCHANGE_LIMIT_REACHED = 760,
    EVENT_EXCHANGE_DUPLICATE_HERO_ID = 762,
    EVENT_EXCHANGE_HERO_NOT_MATCH_RECIPE = 763,
    EVENT_EXCHANGE_ITEM_NOT_MATCH_RECIPE = 764,
    EVENT_EXCHANGE_ARTIFACT_NOT_MATCH_RECIPE = 765,
    EVENT_EXCHANGE_TOO_MANY_MATERIAL = 766,


    EVENT_ARENA_RANK_REQUIREMENT_NOT_FULFILLED = 771,
    EVENT_ARENA_RANK_REWARD_ALREADY_CLAIMED = 772,


    EVENT_SPIN_QUEST_CAN_NOT_SPIN = 780,
    EVENT_SPIN_QUEST_CAN_NOT_REROLL = 781,
    EVENT_SPIN_QUEST_REROLL_LIMIT_REACHED = 782,
    EVENT_SPIN_QUEST_ALL_QUESTS_COMPLETED = 783, --completed ALL quests in event
    EVENT_SPIN_QUEST_NO_QUEST_ASSIGNED = 784, --completed all currently assigned quests.
    EVENT_SPIN_QUEST_NOT_ASSIGNED = 785, --the quest is NOT assign to player, but he tries to claim it.
    EVENT_SPIN_QUEST_NOT_COMPLETED = 786, --player tries to claim the quest reward, but he has not completed it


    EVENT_SERVER_OPEN_PROGRESS_NOT_REACHED = 801,
    EVENT_SERVER_OPEN_PROGRESS_ALREADY_CLAIMED = 802,
    EVENT_SERVER_OPEN_LOCKED = 803,


    EVENT_SALE_OFF_NOT_SUPPORTED = 810,


    EVENT_MID_AUTUMN_LOGIN_ALREADY_CLAIMED = 820,
    EVENT_MID_AUTUMN_EXCHANGE_LIMIT_REACHED = 821,
    EVENT_MID_AUTUMN_GEM_BOX_LIMIT_REACHED = 822,
    EVENT_MID_AUTUMN_FEED_PROCESS_FULL = 823,
    EVENT_MID_AUTUMN_FEED_PROCESS_NOT_ENOUGH = 824,


    EVENT_PASS_NOT_BUY = 840,
    EVENT_PASS_MILE_STONE_OUT_OF_STOCK = 841,
    EVENT_PASS_MILE_STONE_REQUIREMENT_NOT_MET = 842,


    EVENT_HALLOWEEN_LOGIN_ALREADY_CLAIMED = 850,
    EVENT_HALLOWEEN_CLAIM_DAY_INVALID = 851,
    EVENT_HALLOWEEN_EXCHANGE_LIMIT_REACHED = 852,
    EVENT_HALLOWEEN_EXCHANGE_RECIPE_INVALID = 853,


    EVENT_BLACK_FRIDAY_GEM_PACK_INVALID = 860,
    EVENT_BLACK_FRIDAY_GEM_PACK_LIMIT_REACHED = 861,

    EVENT_CHRISTMAS_EXCHANGE_RECIPE_INVALID = 870,
    EVENT_CHRISTMAS_EXCHANGE_LIMIT_REACHED = 871,
    EVENT_CHRISTMAS_CHALLENGE_FORBIDDEN = 872,
    EVENT_CHRISTMAS_FORMATION_INVALID = 873,
    EVENT_CHRISTMAS_NOT_ENOUGH_STAMINA = 874,


    EVENT_NEW_YEAR_GEM_BOX_LIMIT_REACHED = 880,
    EVENT_NEW_YEAR_LOTTERY_NEED_RESET = 881,

    MASTER_SECRET_INVALID = 2000,


    TRACKING_SECRET_INVALID = 2500,


    LOAD_BALANCE_SECRET_INVALID = 3000,
    LOAD_BALANCE_SERVER_FULL = 3001,
    LOAD_BALANCE_SERVER_MAINTENANCE = 3002,

    WAITING_SERVER_RESPONSE_TO_LONG = -1,
}