--- @class OpCode
OpCode = {
    PING = 0,
    SYNC_CLOCK_TIME = 1,
    RECONNECT = 2,
    DISCONNECT = 3,
    UDP_HANDSHAKE = 4,
    UDP_BINDING = 5,
    LOGIN = 6,
    ECHO = 7,
    REGISTER = 8,
    HAND_SHAKE = 9,

    PLAYER_ACCOUNT_BIND = 10,
    PLAYER_ACCOUNT_SWITCH = 11,

    PLAYER_DATA_GET = 20,


    PLAYER_PASSWORD_FORGOT = 25,
    PLAYER_PASSWORD_FORGOT_RESEND = 26,
    PLAYER_PASSWORD_RESET = 27,
    PLAYER_PASSWORD_CHANGE = 28,


    PLAYER_EMAIL_ADD = 30,
    PLAYER_EMAIL_RESEND = 31,
    PLAYER_EMAIL_VERIFY = 32,
    PLAYER_EMAIL_STATUS_GET = 33,

    PLAYER_NAME_CHANGE = 40,
    PLAYER_AVATAR_CHANGE = 41,
    PLAYER_LANGUAGE_CHANGE = 42,
    PLAYER_BLOCK = 43,


    HERO_LEVEL_UP = 50,
    HERO_EVOLVE = 51,
    HERO_LOCK = 52,
    HERO_SKIN_HIDE = 53,
    HERO_SKIN_EQUIP = 54,
    HERO_MULTI_EVOLVE = 55,


    ALTAR_HERO_DISASSEMBLE = 60,
    ALTAR_MARKET_BUY = 61,
    ALTAR_MARKET_REFRESH = 62,
    ALTAR_HERO_RESET = 63,

    REGRESS_HERO = 65,

    SUMMON_HERO = 70,
    SUMMON_HERO_BY_FRAGMENT = 71,


    PROPHET_TREE_SUMMON = 80,
    PROPHET_TREE_CONVERT = 81,
    PROPHET_TREE_SAVE_CONVERTED = 82,


    ITEM_EQUIP = 90,
    ITEM_UPGRADE_ON_BLACKSMITH = 91,
    ITEM_SELL = 93,
    ITEM_EQUIPMENT_UPGRADE_ON_HERO = 94,

    ITEM_ARTIFACT_COMBINE = 100,
    ITEM_ARTIFACT_UPGRADE = 101,

    ITEM_STONE_CONVERT = 110,
    ITEM_STONE_UPGRADE = 111,
    ITEM_STONE_SAVE_CONVERTED = 112,

    ITEM_TALENT_UNLOCK = 115,
    ITEM_TALENT_REFRESH = 116,
    ITEM_TALENT_SELECT = 117,

    CASINO_SPIN = 120,
    CASINO_REFRESH = 121,
    CASINO_CHIP_BUY = 122,
    CASINO_MARKET_BUY = 123,
    CASINO_MARKET_REFRESH = 124,


    CAMPAIGN_ITEM_CLAIM = 131,
    CAMPAIGN_RESOURCE_CLAIM = 132,
    CAMPAIGN_CHALLENGE = 133,
    CAMPAIGN_QUICK_BATTLE_TICKET_USE = 134,
    CAMPAIGN_QUICK_BATTLE = 135,

    CAMPAIGN_TRAINING_HERO_BIND = 140,
    CAMPAIGN_TRAINING_EXP_CLAIM = 141,


    DAILY_REWARD_CLAIM = 150,


    SERVER_LIST_GET = 160,
    SERVER_NOTICE = 161,
    SERVER_OTHER_PLAYER_DETAIL_GET = 163,
    SERVER_OTHER_PLAYER_DETAIL_LIST_GET = 164,


    TOWER_CHALLENGE = 170,
    TOWER_STAMINA_BUY = 171,


    HAND_OF_MIDAS_CLAIM = 180,


    RAID_CHALLENGE = 190,
    RAID_STAMINA_BUY = 191,


    RECORD_LIST_GET = 200,
    RECORD_DETAIL_GET = 201,
    RECORD_REVENGE = 202,
    RECORD_TOWER_DETAIL_GET = 203,
    RECORD_ARENA_TEAM_DETAIL_GET = 204,
    RECORD_ARENA_TEAM_BOT_DETAIL_GET = 205,
    RECORD_DOMAINS_GET = 206,

    DUNGEON_HERO_BIND = 210,
    DUNGEON_SMASH_SHOP_BUY = 211,
    DUNGEON_CHALLENGE = 212,
    DUNGEON_ACTIVE_BUFF_USE = 213,
    DUNGEON_SHOP_BUY = 214,
    DUNGEON_BUFF_GENERATE = 215,
    DUNGEON_BUFF_PICK = 216,

    MASTERY_UPGRADE = 220,
    MASTERY_RESET = 221,


    SUMMONER_CLASS_SELECT = 230,
    SUMMONER_SKILL_TIER_SELECT = 231,
    SUMMONER_EVOLVE = 232,


    TAVERN_QUEST_REROLL = 240,
    TAVERN_QUEST_ADD = 241,
    TAVERN_QUEST_LOCK = 242,
    TAVERN_QUEST_START = 243,
    TAVERN_QUEST_CANCEL = 244,
    TAVERN_QUEST_COMPLETE = 245,
    TAVERN_QUEST_SPEED_UP = 246,


    FRIEND_DELETE = 251,
    FRIEND_SEARCH = 252,

    FRIEND_SEARCH_RECOMMENDATION = 254,

    FRIEND_BOSS_CHALLENGE = 260,
    FRIEND_BOSS_SCOUT = 261,
    FRIEND_BOSS_STATISTICS_GET = 262,
    FRIEND_BOSS_DETAIL_GET = 263,

    FRIEND_REQUEST_ADD = 270,
    FRIEND_REQUEST_MANAGE = 271,

    FRIEND_POINT_SEND = 280,
    FRIEND_POINT_CLAIM = 281,


    ARENA_OPPONENT_FIND = 290,
    ARENA_PREVIOUS_SEASON_RESULT_GET = 291,

    ARENA_CHALLENGE = 300,
    ARENA_FORMATION_SET = 301,
    ARENA_BOT_CHALLENGE = 302,

    ARENA_MARKET_BUY = 310,
    ARENA_TICKET_BUY = 311,
    ARENA_MARKET_UPGRADE = 312,

    CHAT_SEND = 320,
    CHAT_SUBSCRIBE = 321,
    CHAT_UNSUBSCRIBE = 322,
    CHAT_SERVER_SEND = 323,


    MARKET_BUY = 340,
    MARKET_REFRESH = 341,
    MARKET_UPGRADE = 342,


    GUILD_CREATE = 350,
    GUILD_REQUEST_JOIN = 351,
    GUILD_INFO_CHANGE = 352,
    GUILD_APPLICATION_MANAGE = 353,

    GUILD_MEMBER_KICK = 360,
    GUILD_MEMBER_ROLE_CHANGE = 361,
    GUILD_MEMBER_RECRUIT = 362,

    GUILD_LEAVE = 370,
    GUILD_SEARCH = 371,
    GUILD_SEARCH_CANDIDATE = 372,
    GUILD_SEARCH_RECOMMENDATION = 373,

    GUILD_CHECK_IN = 380,

    GUILD_MARKET_BUY = 390,
    GUILD_MARKET_REFRESH = 391,
    GUILD_MARKET_UPGRADE = 392,

    GUILD_BOSS_SELECT = 400,
    GUILD_BOSS_CHALLENGE = 401,
    GUILD_BOSS_MONTHLY_STATISTICS_GET = 402,

    GUILD_DUNGEON_CHALLENGE = 410,
    GUILD_DUNGEON_DETAIL_GET = 411,
    GUILD_DUNGEON_STATISTICS_GET = 413,

    GUILD_WAR_MEMBER_REGISTER = 420,
    GUILD_WAR_REGISTER = 421,
    GUILD_WAR_CHALLENGE = 423,
    GUILD_WAR_OPPONENT_FIND = 424,
    GUILD_WAR_PREVIOUS_BATTLE_RESULT_GET = 425,
    GUILD_WAR_PREVIOUS_SEASON_RESULT_GET = 426,


    MAIL_COMPOSE = 430,
    MAIL_READ = 431,
    MAIL_DELETE = 432,
    MAIL_REWARD_CLAIM = 433,
    MAIL_TRANSACTION_GET = 434,
    MAIL_GET = 435,


    TUTORIAL_SUMMON_HERO = 440,
    TUTORIAL_STEP_SET = 441,


    REMOTE_CONFIG_SET = 450,
    REMOTE_CONFIG_GET = 451,

    ACCOUNT_REMOTE_CONFIG_SET = 455,


    QUEST_DAILY_CLAIM = 460,
    QUEST_ACHIEVEMENT_CLAIM = 461,
    QUEST_TREE_CLAIM = 462,
    QUEST_DATA_GET = 463,


    FACEBOOK_FAN_PAGE_JOIN = 470,


    FORMATION_SET = 480,

    DEFENSE_MODE_SAVE_TOWER_FORMATION = 490,
    DEFENSE_MODE_CHALLENGE = 491,
    DEFENSE_MODE_TOWER_UPGRADE = 492,
    DEFENSE_MODE_CONSTRUCTION_UPGRADE = 493,
    DEFENSE_MODE_IDLE_CLAIM = 494,
    DEFENSE_MODE_IDLE_ITEM_CLAIM = 495,
    DEFENSE_OTHER_RECORD_LIST_GET = 496,
    DEFENSE_RECORD_DETAIL_GET = 497,
    DEFENSE_BATTLE_RECORD_DETAIL_GET = 498,

    PURCHASE_RAW_PACK = 500,
    PURCHASE_PROGRESS_PACK = 501,
    PURCHASE_SUBSCRIPTION_PACK = 502,
    PURCHASE_LIMITED_PACK = 503,
    PURCHASE_SUBSCRIPTION_TRIAL_PACK = 504,
    PURCHASE_GROWTH_PACK = 508,
    PURCHASE_GROWTH_PACK_MILESTONE_CLAIM = 509,

    RAISE_HERO_BIND_RAISED_HEROES = 510,
    RAISE_HERO_UNBIND_RAISED_HEROES = 511,
    RAISE_HERO_UNLOCK_SLOT = 512,
    RAISE_HERO_RESET_COUNTDOWN_SLOT = 513,


    HERO_LINKING_SUPPORT_HERO_SAVE = 520,
    HERO_LINKING_HERO_SAVE = 521,


    PURCHASE_PRODUCT_CHECK = 540,


    GIFT_CODE_CLAIM = 550,


    EVENT_DATA_GET = 600,


    EVENT_LOGIN_CLAIM = 610,


    EVENT_BUNDLE_PURCHASE = 620,


    EVENT_HOT_DEAL_PURCHASE = 630,


    EVENT_RELEASE_FESTIVAL_CLAIM = 640,


    EVENT_EXCHANGE = 650,


    EVENT_ARENA_RANK_CLAIM = 660,


    REWARD_VIDEO = 661,


    EVENT_SPIN_QUEST = 670,
    EVENT_SPIN_QUEST_REROLL = 671,
    EVENT_SPIN_QUEST_CLAIM_REWARD = 672,


    EVENT_GUILD_QUEST_DONATE = 680,
    EVENT_GUILD_QUEST_CLAIM_REWARD = 681,

    EVENT_RATE_UP = 690,


    TRACKING_INFO_GET = 700,

    EVENT_MARKET_BUY = 710,

    EVENT_SERVER_OPEN_MARKET_BUY = 720,
    EVENT_SERVER_OPEN_QUEST_CLAIM = 721,
    EVENT_SERVER_OPEN_PROGRESS_CLAIM = 722,
    EVENT_SALE_OFF_PURCHASE = 730,

    EVENT_MID_AUTUMN_PURCHASE = 740,
    EVENT_MID_AUTUMN_EXCHANGE = 741,
    EVENT_MID_AUTUMN_GEM_BOX_BUY = 742,
    EVENT_MID_AUTUMN_LOGIN_CLAIM = 743,
    EVENT_MID_AUTUMN_BEAST_REWARD_CLAIM = 745,
    EVENT_MID_AUTUMN_FEED_BEAST = 746,


    EVENT_ARENA_PASS_PURCHASE = 760,
    EVENT_ARENA_PASS_MILESTONE_CLAIM = 761,

    EVENT_DAILY_QUEST_PASS_PURCHASE = 770,
    EVENT_DAILY_QUEST_PASS_MILESTONE_CLAIM = 771,

    EVENT_HALLOWEEN_BUNDLE_PURCHASE = 780,
    EVENT_HALLOWEEN_DAILY_CLAIM = 781,
    EVENT_HALLOWEEN_EXCHANGE = 782,
    EVENT_HALLOWEEN_DAILY_PURCHASE = 783,
    EVENT_HALLOWEEN_DICE_ROLL = 784,

    EVENT_BLACK_FRIDAY_GEM_PACK_BUY = 790,
    EVENT_BLACK_FRIDAY_CARD_PURCHASE = 791,

    EVENT_CHRISTMAS_DAILY_LOGIN_CLAIM = 800,
    EVENT_CHRISTMAS_BOX_OPEN = 801,
    EVENT_CHRISTMAS_EXCHANGE_RESOURCE = 802,
    EVENT_CHRISTMAS_DAILY_PURCHASE = 803,
    EVENT_CHRISTMAS_EXCLUSIVE_OFFER_PURCHASE = 804,
    EVENT_CHRISTMAS_CHALLENGE_BOSS = 805,
    EVENT_CHRISTMAS_RANKING_GET = 806,


    EVENT_NEW_YEAR_BOX_BUY = 810,
    EVENT_NEW_YEAR_DAILY_BUNDLE_PURCHASE = 811,
    EVENT_NEW_YEAR_CARD_PURCHASE = 812,
    EVENT_NEW_YEAR_LOTTERY_ROLL = 813,
    EVENT_NEW_YEAR_LOTTERY_RESET = 814,

    EVENT_LUNAR_NEW_YEAR_DAILY_LOGIN_CLAIM = 820,
    EVENT_LUNAR_NEW_YEAR_ELITE_STORE_PURCHASE = 821,
    EVENT_LUNAR_NEW_YEAR_EXCHANGE = 822,
    EVENT_LUNAR_ELITE_SUMMON = 823,
    EVENT_LUNAR_ELITE_WISH_SELECT = 824,
    EVENT_LUNAR_ELITE_SKIN_BUNDLE_PURCHASE = 825,

    EVENT_LUNAR_NEW_YEAR_DICE_ROLL = 830,
    EVENT_LUNAR_NEW_YEAR_LUNAR_SHOP_EXCHANGE = 831,
    EVENT_LUNAR_NEW_YEAR_QUEST_CLAIM = 832,
    EVENT_LUNAR_NEW_YEAR_BOSS_DETAIL_GET = 833,
    EVENT_LUNAR_NEW_YEAR_BOSS_STATISTICS_GET = 834,
    EVENT_LUNAR_NEW_YEAR_BOSS_CHALLENGE = 835,
    EVENT_LUNAR_NEW_YEAR_BOSS_RANKING_GET = 836,
    EVENT_LUNAR_NEW_YEAR_LUNAR_PATH_STORE_PURCHASE = 837,


    EVENT_VALENTINE_LOGIN_CLAIM = 840,
    EVENT_VALENTINE_BOSS_CHALLENGE = 841,
    EVENT_VALENTINE_STAMINA_BUY = 842,
    EVENT_VALENTINE_LOVE_BUNDLE_PURCHASE = 843,
    EVENT_VALENTINE_SKIN_BUNDLE_PURCHASE = 844,
    EVENT_VALENTINE_ELITE_BUNDLE_PURCHASE = 845,
    EVENT_VALENTINE_WISH_CARD_SELECT = 846,
    EVENT_VALENTINE_CARD_OPEN = 847,

    EVENT_COMMUNITY_DATA_GET = 850,
    EVENT_COMMUNITY_REWARD_CLAIM = 851,

    EVENT_NEW_HERO_QUEST_CLAIM = 860,
    EVENT_NEW_HERO_LOGIN_CLAIM = 861,
    EVENT_NEW_HERO_SPIN = 862,
    EVENT_NEW_HERO_SUMMON = 863,
    EVENT_NEW_HERO_SUMMON_QUEST_CLAIM = 864,
    EVENT_NEW_HERO_BUNDLE_PURCHASE = 865,
    EVENT_NEW_HERO_COLLECTION_QUEST_CLAIM = 866,
    EVENT_NEW_HERO_ROSE_BUY = 867,
    EVENT_NEW_HERO_EXCHANGE = 868,
    EVENT_NEW_HERO_CHALLENGE = 869,

    EVENT_SERVER_MERGE_DAILY_QUEST_CLAIM = 870,
    EVENT_SERVER_MERGE_LOGIN_CLAIM = 871,
    EVENT_SERVER_MERGE_EXCHANGE = 872,
    EVENT_SERVER_MERGE_ACCUMULATE_QUEST_CLAIM = 873,
    EVENT_SERVER_MERGE_BUNDLE_ITEM_SELECT = 874,
    EVENT_SERVER_MERGE_BUNDLE_PURCHASE = 875,

    EVENT_EASTER_LOGIN_CLAIM = 880,
    EVENT_EASTER_CARD_PURCHASE = 881,
    EVENT_EASTER_LIMIT_OFFER_PURCHASE = 882,
    EVENT_EASTER_DAILY_BUNDLE_PURCHASE = 883,
    EVENT_EASTER_EGG_BREAK = 884,
    EVENT_EASTER_EGG_EXCHANGE = 885,

    EVENT_NEW_HERO_BOSS_RANKING_GET = 890,
    EVENT_NEW_HERO_RATE_UP_SUMMON = 891,
    EVENT_NEW_HERO_SKIN_BUNDLE_PURCHASE = 892,

    EVENT_BIRTHDAY_LOGIN_CLAIM = 900,
    EVENT_BIRTHDAY_DAILY_BUNDLE_PURCHASE = 901,
    EVENT_BIRTHDAY_ANNIVERSARY_OFFER_PURCHASE = 902,
    EVENT_BIRTHDAY_EXCHANGE = 903,
    EVENT_BIRTHDAY_WHEEL_SPIN = 904,
    EVENT_BIRTHDAY_WHEEL_CLAIM = 905,

    EVENT_BIRTHDAY_ISLAND_UNLOCK = 910,
    EVENT_BIRTHDAY_LINE_COMPLETE_REWARD = 911,
    EVENT_NEW_HERO_TREASURE_REWARD_BUY = 912,

    EVENT_SKIN_BUNDLE_PURCHASE = 920,

    FAKE_DATA = 1000,
    FAKE_SUMMON_MASS = 1001,
    FAKE_CONVERT_MASS = 1002,
    FAKE_CASINO_SPIN = 1003,
    FAKE_CLEAR_SUMMON_PRODUCTION = 1004,
    FAKE_CLEAR_EVENT_RATE_UP_SUMMON = 1005,
    FAKE_EVENT_RATE_UP_SUMMON_MASS = 1006,

    SUN_GAME_LOGIN = 1100,
    SUN_GAME_PENDING_ORDER_GET = 1101,

    ARENA_TEAM_FORMATION_SAVE = 1500,
    ARENA_TEAM_OPPONENT_FIND = 1501,
    ARENA_TEAM_RANKING_GET = 1502,
    ARENA_TEAM_CHALLENGE = 1503,
    ARENA_TEAM_BOT_CHALLENGE = 1504,
    ARENA_TEAM_OPPONENT_DETAIL_GET = 1505,
    ARENA_TEAM_PREVIOUS_SEASON_RESULT_GET = 1506,
    ARENA_TEAM_TICKET_BUY = 1507,
    ARENA_TEAM_MARKET_BUY = 1508,
    ARENA_TEAM_MARKET_UPGRADE = 1509,

    COMEBACK_DAILY_LOGIN = 1510,
    COMEBACK_DAILY_QUEST = 1511,
    COMEBACK_BUNDLE_PURCHASE = 1512,

    DOMAINS_CONTRIBUTE_HERO_SAVE = 1520,
    DOMAINS_CREW_CREATE = 1523,
    DOMAINS_CREW_LEADER_CHANGE = 1524,
    DOMAINS_CREW_DELETE = 1525,
    DOMAINS_CREW_MEMBER_KICK = 1526,
    DOMAINS_CREW_DATA_GET = 1527,

    DOMAINS_MEMBER_SEARCH = 1530,
    DOMAINS_MEMBER_INVITE = 1531,
    DOMAINS_MEMBER_HERO_DETAIL_GET = 1532,
    DOMAINS_MEMBER_INVITATIONS_GET = 1533,
    DOMAINS_MEMBER_INVITATION_MANAGE = 1534,

    DOMAINS_CREW_SEARCH = 1540,
    DOMAINS_CREW_APPLICATION_GET = 1541,
    DOMAINS_CREW_RECOMMENDATION_GET = 1542,
    DOMAINS_CREW_APPLICATION_MANAGE = 1543,
    DOMAINS_CREW_APPLICATION_SEND = 1544,
    DOMAINS_CREW_MEMBER_LEAVE = 1545,
    DOMAINS_CREW_MEMBER_READY_UPDATE = 1546,
    DOMAINS_CREW_APPLICATION_DELETE_ALL = 1547,
    DOMAINS_OPEN_CHEST = 1548,

    CREW_MEMBER_DETAIL_GET = 1550,
    DOMAINS_MEMBER_RECRUIT = 1551,

    CREW_BATTLE_START = 1555,
    CREW_CHALLENGE = 1556,
    CREW_SAVE_CHALLENGE_FORMATION = 1557,

    MASTER_SERVER_ACTION = 2000,


    TRACKING_SERVER_ACTION = 2500,


    LOAD_BALANCE_SERVER_ACTION = 3000,


    ---- Client OpCode
    SEED_INFO_COMPLETED = 10999,
}