--- @class BattleConstants
BattleConstants = {
    MAX_ROUND = 15,

    MAX_NUMBER_VALUE = 2 ^ 32,

    MAX_MISS_CHANCE = 0.8,
    MAX_ATTACK_DEBUFF_STAT = 0.2,

    MAX_DAMAGE_REDUCTION_STAT = 0.8,
    MAX_REDUCE_DAMAGE_REDUCTION_STAT = 0.8,
    MAX_ARMOR_BREAK_STAT = 1,
    MAX_CRIT_RATE_STAT = 1,
    MAX_CC_RESISTANCE_STAT = 1,

    NOT_EXISTED_COMPANION_BUFF_ID = -1,

    ATTACKER_TEAM_ID = 1,
    DEFENDER_TEAM_ID = 2,

    BASIC_ATTACK_MULTIPLIER = 1,
    DEFENSE_MULTIPLIER = 0.0001,

    BEFORE_ROUND_ACTION_POSITION = 1,
    BEFORE_TURN_ACTION_POSITION = 2,
    AFTER_TURN_ACTION_POSITION = 3,
    AFTER_ROUND_ACTION_POSITION = 4,

    NUMBER_SLOT = 5,
    NUMBER_SLOT_PER_LINE = 4,
}

return BattleConstants