--- @type CS.UnityEngine
UnityEngine = CS.UnityEngine
--- @type UnityEngine_Application
U_Application = UnityEngine.Application
--- @type UnityEngine_RuntimePlatform
U_RuntimePlatform = UnityEngine.RuntimePlatform
--- @type UnityEngine_Vector2
U_Vector2 = UnityEngine.Vector2
--- @type UnityEngine_Vector3
U_Vector3 = UnityEngine.Vector3
--- @type UnityEngine_Rect
U_Rect = UnityEngine.Rect
--- @type UnityEngine_SystemInfo
U_SystemInfo = UnityEngine.SystemInfo
--- @type UnityEngine_Mathf
U_Mathf = UnityEngine.Mathf
--- @type UnityEngine_Color
U_Color = UnityEngine.Color
--- @type UnityEngine_Resources
U_Resources = UnityEngine.Resources
--- @type UnityEngine_WaitForSeconds
U_WaitForSeconds = UnityEngine.WaitForSeconds
--- @type UnityEngine_WaitForEndOfFrame
U_WaitForEndOfFrame = UnityEngine.WaitForEndOfFrame
--- @type UnityEngine_WaitUntil
U_WaitUntil = UnityEngine.WaitUntil
--- @type UnityEngine_WaitWhile
U_WaitWhile = UnityEngine.WaitWhile
--- @type UnityEngine_EventSystems
U_EventSystems = UnityEngine.EventSystems
--- @type UnityEngine_Screen
U_Screen = UnityEngine.Screen
--- @type UnityEngine_Object
U_Object = UnityEngine.Object
--- @type UnityEngine_GameObject
U_GameObject = UnityEngine.GameObject
--- @type DG_Tweening_Ease
U_Ease = CS.DG.Tweening.Ease
--- @type UnityEngine_RenderTexture
U_RenderTexture = UnityEngine.RenderTexture
--- @type UnityEngine_RenderTextureFormat
U_RenderTextureFormat = UnityEngine.RenderTextureFormat
--- @type UnityEngine_RectTransform_Axis
U_Rect_Axis = UnityEngine.RectTransform.Axis
--- @type UnityEngine_Shader
U_Shader = UnityEngine.Shader
--- @type UnityEngine_Camera
U_Camera = UnityEngine.Camera
--- @type UnityEngine_MaterialPropertyBlock
U_MaterialPropertyBlock = UnityEngine.MaterialPropertyBlock
--- @type UnityEngine_PlayerPrefs
U_PlayerPrefs = UnityEngine.PlayerPrefs
--- @type UnityEngine_Time
U_Time = UnityEngine.Time
--- @type UnityEngine_SystemInfo
U_SystemInfo = UnityEngine.SystemInfo
--- @type UnityEngine_TextAnchor
U_TextAnchor = UnityEngine.TextAnchor
--- @type CS_GameUtils
U_GameUtils = CS.GameUtils
--- @type UnityEngine_LogType
U_LogType = UnityEngine.LogType
--- @type UnityEngine_SystemLanguage
U_SystemLanguage = UnityEngine.SystemLanguage
--- @type CS_FacebookUtils
U_FacebookUtils = CS.FacebookUtils
--- @type CS_PlatformLoginUtils
U_PlatformLoginUtils = CS.PlatformLoginUtils
--- @type CS_BetterStreamingAssets
U_BetterStreamingAssets = CS.BetterStreamingAssets

